
# Synthwave '84-inspired Kitty Theme

# The basic colors
foreground              #e2e8ff
background              #010101
selection_foreground    #2a2139
selection_background    #f4f3cd

# Cursor colors
cursor                  #ffafff
cursor_text_color       #2a2139

# URL underline color when hovering with mouse
url_color               #ffafff
url_style               dashed

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Colors for marks (marked text in the terminal)
mark1_foreground #2a2139
mark1_background #7d4eae
mark2_foreground #2a2139
mark2_background #7d4eae
mark3_foreground #2a2139
mark3_background #7d4eae

# The 16 terminal colors

# black
color0 #1a1b27
color8 #3c3f58

# red
color1 #ff517d
color9 #ff517d

# green
color2  #8cffd1
color10 #8cffd1

# yellow
color3  #fede5d
color11 #ffd36e

# blue
color4  #65baff
color12 #65baff

# magenta
color5  #ff87d4
color13 #ff87d4

# cyan
color6  #78faff
color14 #78faff

# white
color7  #ffffff
color15 #ffffff

# Cursor settings
cursor_stop_blinking_after 0
cursor_blink_interval 0.3 ease
cursor_trail 0
cursor-trail_decay 0.2 0.4
cursor_trail_start_treshold 1
cursor_trail_color #78faff
